### ISSUE TITLE
All aboard!

### ISSUE THREAD

**Issue by AdminAtAptly** [AptlyOrg/jobs#2]
There will be several steps to walk through before you can start playing with code.  Some of the steps you may already know, but I will assume most of this is new to you.  

We can start slow and make sure everything is working with your Pi configuration, if that is what you decide to use for your work.  This will be new for me, too, so we will both be learning a lot.

Early on, it will be more important that you understand why we are doing each step than it is to go fast or or learn everything there is to know.  

After this first ticket there will just be one task per ticket and we can work it through to completion.   We can discuss any problems you run into, but it is always a good idea to start a discussion by adding a comment to your ticket that explains what you are trying to accomplish, the steps you took, and the results(good or bad).  The ticket will also be our primary way to communicate.  If you have a problem or want to discuss something that is hard to describe we can schedule a time to voice chat or screen share, but this should come only after you have updated the tickets with the findings of your own research.  Frustration will come quickly and often, but don't let it discourage you.  If there is something you still don't quite get after your research, I would set it down for a bit and come back to it later.  If upon your return you are still confused or frustrated then that is a good sign that we should discuss.

As you know, Google can be your best friend when learning new topics!  Any links that you come across with useful information are also good for adding to the comments in work tickets.  If you are like me and forget how you fixed something before, you can always look back at the ticket to refresh your memory... and the rest of the team can learn from your research as well. 

Our first steps will look something like this.  Look for the "**Success**:" for each item, it will tell you that you are far enough along to move to the next step:

1.  **Finding the command line on your system and learn how to edit a file and save it.** -- you will quickly grow out of using this regularly, but it is initially important to understand how/when to use the command line.   **Success**: Determine the name of your home directory. Learn one use of each of the following commands:  man, ls, cd, pwd, vi    hint: "man" is a command used to learn about all of the other commands (e.g. typing "man ls" on the command line will tell you what the "ls" command does and how to use it)  **Helpful link**:   [Command line basics](https://www.raspberrypi.org/documentation/usage/terminal/)
1.  **Installing "Git" and connecting to GitHub** -- "Git" is the primary tool you will use check in and check out code.  Think of this command as a library card used to check things in and out of the library.  Think of GitHub as the library itself where your code is stored until you, or someone else, needs to check it out again.  **Success**: This might be already installed on your Pi, but you know its working when you run the following from within your home directory from the command line:
```git clone https://github.com/AptlyOrg/jobs.git```...and a new directory appears in your home directory called "jobs" with several files under it.  **Helpful link**:  [Install Git](https://gist.github.com/manwar/56bb253c5e3ab115d253)
1.  **Understand GitHub Tickets(like this one) and how to add comments** --  Learning how to interact with the tickets are important so we can communicate clearly without talking directly.  **Success**:  Add several test comments to this ticket:  one that adds a link, one that adds a screenshot, and one that quotes code using one of the commands in your first task above.  **Helpful link**:  [Markdown](https://guides.github.com/features/mastering-markdown/) -- [GitHub Style](https://help.github.com/articles/basic-writing-and-formatting-syntax/)

If you can add a comment to this ticket suggest a time at the end of the week that you can voice chat I will setup a call and we can walk through how you did and answer any questions.  

I realize that this will be a lot of work and that some of these items will be hard, but we have to start somewhere.  Based on your progress we will determine what your next steps should be.

**Comment by Traizen** [comment]
Took a look through #1 and the command basics link, read through and took a crack at all of them except for vi and the 'other commands' at the bottom which I will be coming back to. On #2 I was able to get Git installed then got this error 

Cloning into 'jobs'...
fatal: Unable to find remote helper for 'https'

I did a [Google search](https://duckduckgo.com/?q=Cloning+into+%27jobs%27...+fatal%3A+Unable+to+find+remote+helper+for+%27https%27&t=raspberrypi&ia=qa) of the error, will research this further tomorrow.

**Comment by Traizen** [comment]
![2018-01-03-202619_1920x1200_scrot](https://user-images.githubusercontent.com/35007710/34547966-83b41f96-f0c4-11e7-9e85-54791f670f72.png)

Got Git working after some extensive research of the error from earlier. It was missing Curl, which wasn't properly installed. I'm still working on the command research and learning how to quote code.

**Comment by Traizen** [comment]
One of the commands I used was:
```
man
```

Which let me see what the other commands did such as:

```
ls
cd
pwd
```

Examples:
```
man ls
man la -a
man cd
man pwd
```
