### ISSUE TITLE
Choose an IDE or editor and setup your jobs directory as a project within.

### ISSUE THREAD

**Issue by AdminAtAptly** [AptlyOrg/jobs#4]
I primarily use one of these IDEs(Integrated Development Environment):
WebStorm -- https://www.jetbrains.com/webstorm/
IntelliJ -- https://www.jetbrains.com/idea/features/editions_comparison_matrix.html

The problem with these are they are expensive $100s/year.  However, IntelliJ's community version is free and supports everything in our current project, including Python which is what your interested and where this project is heading.  So, might be a good choice.  Otherwise any editor will do, I bet your M&D has some good suggestions to consider.  

Although I think its very important to understand how the command line works, I also think its a lot of work just to do something simple like edit a file.  Most IDEs, have an integrated command line tool built-in, so we can still develop those skills, but if we want to change a file all we have to do is click!  (no vi !!!)   Also, I sometimes forget how confusing git can be, even after using it for a while.  IDEs also make using git MUCH easier.

Once you have a tool in place, you can move this ticket to done and we can schedule another session to review.  

I will let you schedule our next meeting, since I didn't do a very good job.  Hopefully, you can find a tool that works with your Pi to screenshare.

**Comment by AdminAtAptly** [comment]
UPDATE:
woot!
Check this out -- https://www.jetbrains.com/student/

> Get access to all desktop products including IntelliJ IDEA Ultimate, ReSharper Ultimate and other IDEs. All you need to apply is to be a student and have access to your student email address or a valid ISIC card.

This means you can play with these goodies for free as well(Python-specific support):
https://www.jetbrains.com/pycharm/
https://www.jetbrains.com/pycharm-edu/

**Comment by Traizen** [comment]
Checked out the JetBrains student license, looks to be for college students, but I sent in a custom application providing them with some information and reason as to why I believe I'm qualified for a complimentary student license. It will take up to a week for them to review my application and get back with me. Also I have moved over to the Mac mini because of complications with running IDEs on the pi. I'm working now on getting git installed on the Mac as I have on the pi, and get it connected to the repository again.

**Comment by AdminAtAptly** [comment]
Yeah, the mini will probably make things easier while you are starting out.  I guess you can always mount your pi home drive to the mini and use the mini just for running the ide and screenshare stuff. Then you wouldn't lose all your good work on the pi, plus, for the type of work we are doing, real world servers will probably look more like the pi than the mini... great stuff to learn.

After you get things where you like them, I thought we could do a code review of jobs.sh and just walk through line-by-line, so you know how the thing works now.

Just let me know when you want to hook up for screenshare.

**Comment by Traizen** [comment]
Sounds good. I will let you know a time that I am free.
